version: "3.1"

services:
  byte-db:
    image: postgres:10.13-alpine
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: byte
      PGDATA: /data/postgres
    ports:
      - 5432:5432
